openapi: 3.0.0
paths:
  /api/v1:
    get:
      operationId: getHello
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: string
      tags:
        - app
  /api/v1/external-api-rxjs:
    get:
      operationId: getObservable
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - app
  /api/v1/external-api-promise:
    get:
      operationId: getPromise
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - app
  /api/v1/songs:
    post:
      operationId: createSong
      summary: Create a song
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSongDto"
      responses:
        "201":
          description: The song has been created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindSongDto"
        "404":
          description: Song not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AllExceptionsResponseDto"
      tags:
        - songs
    get:
      operationId: findAllSongs
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FindSongDto"
      tags:
        - songs
  /api/v1/songs/{id}:
    get:
      operationId: findSongById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindSongDto"
      tags:
        - songs
    put:
      operationId: updateSongById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSongDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindSongDto"
      tags:
        - songs
    delete:
      operationId: deleteSongById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags:
        - songs
  /api/v1/albums:
    post:
      operationId: createAlbum
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAlbumDto"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindAlbumDto"
      tags:
        - albums
    get:
      operationId: findAllAlbums
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FindAlbumDto"
      tags:
        - albums
  /api/v1/albums/{id}:
    get:
      operationId: findAlbumById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindAlbumDto"
      tags:
        - albums
    put:
      operationId: updateAlbumById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAlbumDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindAlbumDto"
      tags:
        - albums
    delete:
      operationId: deleteAlbumById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags:
        - albums
info:
  title: Spotify Clone API - MongoDB
  description: freeCodeCamp - NestJS Complete Course API
  version: "1.0"
  contact: {}
tags: []
servers:
  - url: http://localhost:3001
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
      description: Enter JWT token
  schemas:
    CreateSongDto:
      type: object
      properties:
        title:
          type: string
        releasedDate:
          format: date-time
          type: string
        duration:
          type: string
        lyrics:
          type: string
        album:
          type: string
      required:
        - title
        - releasedDate
        - duration
        - lyrics
    FindSongDto:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        releasedDate:
          format: date-time
          type: string
        duration:
          type: string
        lyrics:
          type: string
        album:
          $ref: "#/components/schemas/FindAlbumDto"
      required:
        - id
        - title
        - releasedDate
        - duration
        - lyrics
        - album
    FindAlbumDto:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        songs:
          type: array
          items:
            $ref: "#/components/schemas/FindSongDto"
      required:
        - id
        - title
        - songs
    AllExceptionsResponseDto:
      type: object
      properties:
        message:
          type: object
        name:
          type: object
        path:
          type: object
        statusCode:
          type: number
        timestamp:
          type: string
      required:
        - message
        - name
        - path
        - statusCode
        - timestamp
    UpdateSongDto:
      type: object
      properties:
        title:
          type: string
        releasedDate:
          format: date-time
          type: string
        duration:
          type: string
        lyrics:
          type: string
        album:
          type: string
    CreateAlbumDto:
      type: object
      properties:
        title:
          type: string
        songs:
          type: array
          items:
            type: string
      required:
        - title
        - songs
    UpdateAlbumDto:
      type: object
      properties:
        title:
          type: string
        songs:
          type: array
          items:
            type: string
